---
root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - airbnb-base
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .ts

env:
  browser: true
  node: true

rules:
  arrow-parens:
    - 2
    - as-needed
  import/extensions: 0
  import/order:
    - 2
    - groups:
        - - builtin
          - external
        - parent
        - sibling
        - index
      newlines-between: always
  import/prefer-default-export: 0
  indent:
    - 2
    - tab
  no-console:
    - 2
    - allow:
        - info
        - error
  no-tabs: 0
